export const fakeData = [
  {
    id: 1,
    firstName: "Tera",
    lastName: "Bygreaves",
    email: "tbygreaves0@jiathis.com",
    state: "Nevada",
    address: "23804 Randy Court",
  },
  {
    id: 2,
    firstName: "Blair",
    lastName: "Dabbes",
    email: "bdabbes1@twitter.com",
    state: "Connecticut",
    address: "4 Pond Court",
  },
  {
    id: 3,
    firstName: "Case",
    lastName: "Davydzenko",
    email: "cdavydzenko2@sphinn.com",
    state: "District of Columbia",
    address: "98 Summit Drive",
  },
  {
    id: 4,
    firstName: "Noe",
    lastName: "Worshall",
    email: "nworshall3@usnews.com",
    state: "Tennessee",
    address: "10636 Corry Street",
  },
  {
    id: 5,
    firstName: "Erhard",
    lastName: "Chasteney",
    email: "echasteney4@about.com",
    state: "Illinois",
    address: "65 Riverside Circle",
  },
  {
    id: 6,
    firstName: "Norry",
    lastName: "Counihan",
    email: "ncounihan5@alexa.com",
    state: "Massachusetts",
    address: "632 Cordelia Avenue",
  },
  {
    id: 7,
    firstName: "Stafani",
    lastName: "Kennefick",
    email: "skennefick6@meetup.com",
    state: "Texas",
    address: "8730 Tomscot Center",
  },
  {
    id: 8,
    firstName: "Harri",
    lastName: "Yoodall",
    email: "hyoodall7@instagram.com",
    state: "Texas",
    address: "45 Michigan Plaza",
  },
  {
    id: 9,
    firstName: "Chantalle",
    lastName: "Guion",
    email: "cguion8@apache.org",
    state: "Kansas",
    address: "8 Crownhardt Terrace",
  },
  {
    id: 10,
    firstName: "Waldo",
    lastName: "Hansill",
    email: "whansill9@china.com.cn",
    state: "New Jersey",
    address: "4821 Havey Road",
  },
];
